### ISSUE TITLE
How can i use it on Jetson Nano? 

### ISSUE THREAD

**Issue by feefro** [bmegli/realsense-network-hardware-video-encoder#28]
I am intrested in try your encoding work with Jetson Nano.
Unfortunately as i understood it does not support encoding on ffmpeg (https://trac.ffmpeg.org/ticket/7924)
Do you have suggestions?

**Comment by bmegli** [comment]
Hi @feefro,

RNHVE uses VAAPI for encoding. 
It will not work with Jetson Nano and probably won't work with NVIDIA at all.

This is summarized [here](https://github.com/bmegli/realsense-network-hardware-video-encoder/wiki/Hardware), linked from readme `hardware` section.

VAAPI-VDPAU bridge will likely only get you limited support for decoding (not encoding).
[nouveau](https://nouveau.freedesktop.org/VideoAcceleration.html) has some support for VAAPI but it also seems to be only decoding side (I am not certain about that).

--------------------

Forgetting about RNHVE (which will not work on Jetson Nano at this time).

Jetson Nano has [dedicated hardware](https://forums.developer.nvidia.com/t/h-264-h-265-encoding-using-jetson-nano-gpu/73839/4) for accelerated encoding/decoding (apart from GPU). 

If you want to stream video with hardware encoding it should probably be easiest with gstreamer.

**Comment by bmegli** [comment]
@feefro,

> Forgetting about RNHVE (which will not work on Jetson Nano at this time).
> Jetson Nano has dedicated hardware for accelerated encoding/decoding (apart from GPU).
> If you want to stream video with hardware encoding it should probably be easiest with gstreamer.

Follow [this comment](https://forums.developer.nvidia.com/t/h-264-h-265-encoding-using-jetson-nano-gpu/73839/2) recommendation

**Comment by bmegli** [comment]
I am closing the issue.

Feel free to reopen it if you have some question related to it.
